<?php /** @var \Tuna\WysiwygInitialer\Block\Wysiwyg $block  */ ?>
<textarea id="default-my-wysiwyg" name="my-wysiwyg" cols="5" rows="3" class="textarea"></textarea>

<script>
    require([
        'jquery',
        'wysiwygAdapter',
        'mage/adminhtml/wysiwyg/tiny_mce/setup',
        'domReady!'
    ], function (jQuery, wysiwygAdapter, wysiwygSetup) {
        'use strict';

        var editor4;

        <?php if(strpos($block->getCurrentEditorPath(),'tinymce4Adapter')) : ?>
            console.log('tinymce4 loaded!');

            editor4 = tinymce.init({
                selector: '#default-my-wysiwyg',
            });

            console.log(editor4);

        <?php elseif (strpos($block->getCurrentEditorPath(),'tinymce3Adapter')) : ?>
            console.log('tinymce3 loaded!');
            editor = tinymce.init({
                mode : "exact",
                theme : "advanced",
                elements : "my-wysiwyg",
                plugins : "inlinepopups,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
                theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
                theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
                theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
                theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,|,visualchars,nonbreaking",
                theme_advanced_toolbar_location : "top",
                theme_advanced_toolbar_align : "left",
                theme_advanced_path_location : "bottom",
                extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
                theme_advanced_resize_horizontal : 'false',
                theme_advanced_resizing : 'true',
                apply_source_formatting : 'true',
                convert_urls : 'false',
                force_br_newlines : 'true',
                height: 400,
                toolbar: 'undo redo | formatselect | bold italic forecolor | alignleft aligncenter alignright alignjustify | removeformat',
            });

        <?php endif; ?>
    });
</script>
