<?php /** @var \Tuna\WysiwygInitialer\Block\Wysiwyg $block  */ ?>
<?php
$config = $block->getWysiwygConfig();
?>
<p><?php echo $block->getCurrentEditorPath() ?></p>
<textarea id="my-wysiwyg" name="my-wysiwyg" cols="5" rows="3" class="textarea"></textarea>
<textarea id="my-wysiwyg2" name="my-wysiwyg2" cols="5" rows="3" class="textarea textarea2"></textarea>
<textarea id="my-wysiwyg3" name="my-wysiwyg3" cols="5" rows="3" class="textarea textarea3"></textarea>
<textarea id="my-wysiwyg4" name="my-wysiwyg4" cols="5" rows="3" class="textarea textarea4"></textarea>

<script>
    require([
        'jquery',
        'wysiwygAdapter',
        'mage/adminhtml/wysiwyg/tiny_mce/setup',
        'domReady!'
    ], function (jQuery, wysiwygAdapter, wysiwygSetup) {
        'use strict';

        console.log(tinymce); // Global variable tinymce
        console.log(tinyMCE);
        console.log(wysiwygAdapter);
        console.log(wysiwygSetup);

        var editor, editor2, editor3, editor4, config;

        <?php if(strpos($block->getCurrentEditorPath(),'tinymce4Adapter')) : ?>
        console.log('tinymce4 loaded!');
        editor = new wysiwygSetup("my-wysiwyg", <?php echo json_encode($block->getWysiwygConfig()->getData()) ?>);
        console.log('wysiwyg instance ' + editor.wysiwygInstance);
        editor.wysiwygInstance.setup('exact');

        editor2 = new wysiwygSetup("my-wysiwyg2", <?php echo json_encode($block->getWysiwygConfig()->getData()) ?>);
        console.log('wysiwyg instance ' + editor2.wysiwygInstance);
        editor2.wysiwygInstance.setup('exact');

        editor3 = tinyMCE.init({
            selector: '#my-wysiwyg3'
        });

        console.log(editor3);

        editor4 = tinymce.init({
            selector: '#my-wysiwyg4',
            height: 400,
            menubar: "tools",
            plugins: [
                'advlist autolink lists link image charmap print preview anchor textcolor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table paste code help wordcount'
            ],
            toolbar: 'undo redo | formatselect | bold italic forecolor | alignleft aligncenter alignright alignjustify | removeformat | spellchecker',
            spellchecker_callback: function (method, text, success, failure) {
                var words = text.match(this.getWordCharPattern());
                if (method === "spellcheck") {
                    var suggestions = {};
                    for (var i = 0; i < words.length; i++) {
                        suggestions[words[i]] = ["First", "Second"];
                    }
                    success({ words: suggestions, dictionary: [ ] });
                } else if (method === "addToDictionary") {
                    // Add word to dictionary here
                    success();
                }
            }
        });

        console.log(editor4);

        <?php elseif (strpos($block->getCurrentEditorPath(),'tinymce3Adapter')) : ?>
        console.log('tinymce3 loaded!');
        editor = tinymce.init({
            mode : "exact",
            theme : "advanced",
            elements : "my-wysiwyg",
            plugins : "inlinepopups,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
            theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,|,visualchars,nonbreaking",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_path_location : "bottom",
            extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
            theme_advanced_resize_horizontal : 'false',
            theme_advanced_resizing : 'true',
            apply_source_formatting : 'true',
            convert_urls : 'false',
            force_br_newlines : 'true',
            height: 400,
            toolbar: 'undo redo | formatselect | bold italic forecolor | alignleft aligncenter alignright alignjustify | removeformat',
        });

        <?php endif; ?>


    });
</script>
